title: Personal Dotfile setup
description: Contains config for full terminal setup with zsh, ssh and tooling.
theme: just-the-docs

url: https://NiklasHargarter.github.io/dotfiles

aux_links:
  Github Repository: https://github.com/NiklasHargarter/dotfiles
